# Site settings
title: Cloud Consultant
email: rene@warnke.cloud
url: warnke.cloud
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Cloud Beratung - Plattform Lead - Projekt Management"
meta_author: Warnke Rene

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rene Warnke
  location: Hamburg
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: mastodon
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
  - title: github
    url: http://github.com/renewarnke

# Postal address (add as many lines as necessary)
address:
  - line: Sietwende 67
  - line: 21037, Hamburg

# Credits content
Impressum: '<h1>Impressum</h1>

<p>Rene Warnke<br />
IT Consulting<br />
Musterstra&szlig;e 111<br />
Geb&auml;ude 44<br />
90210 Musterstadt</p>

<h2>Kontakt</h2>
<p>Telefon: +49 (0) 123 44 55 66<br />
Telefax: +49 (0) 123 44 55 99<br />
E-Mail: mustermann@musterfirma.de</p>

<h2>Umsatzsteuer-ID</h2>
<p>Umsatzsteuer-Identifikationsnummer gem&auml;&szlig; &sect; 27 a Umsatzsteuergesetz:<br />
DE999999999</p>

<h2>Berufsbezeichnung und berufsrechtliche Regelungen</h2>
<p>Berufsbezeichnung:<br />
IT Berater</p>
<p>Verliehen in:<br />
Deutschland</p>
<h2>Verbraucher&shy;streit&shy;beilegung/Universal&shy;schlichtungs&shy;stelle</h2>
<p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>

<p>Quelle: <a href="https://www.e-recht24.de">https://www.e-recht24.de</a></p>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
